python: can't open file '/tmp/gptme-evals-0neggzso/hello.py': [Errno 2] No such file or directory
