python: can't open file '/tmp/gptme-evals-neghulcw/prime.py': [Errno 2] No such file or directory
