python: can't open file '/tmp/gptme-evals-jte5nxfg/hello.py': [Errno 2] No such file or directory
