python: can't open file '/tmp/gptme-evals-ts6m9mqk/hello.py': [Errno 2] No such file or directory
