python: can't open file '/tmp/gptme-evals-n_bjc478/hello.py': [Errno 2] No such file or directory
