python: can't open file '/tmp/gptme-evals-whzuihvi/hello.py': [Errno 2] No such file or directory
